baseURL = 'http://beta.incaya.fr/'
defaultContentLanguage = "fr"
title = "Incaya"

[social]
github = "https://github.com/incaya"
twitter = "https://twitter.com/incayascop"

[params]
author = "Incaya"
bio = "Société coopérative de services du numérique"
description = "A vos côtés pour inventer ! Associations, collectivités, entreprises : nous assurons l'Assistance à Maîtrise d'Ouvrage (AMO SI) de votre projet de création ou de refonte de système d'information. Spécialistes de la veille et de l'innovation technique, nous vous conseillons et réalisons des prototypes logiciels et matériels pour vos projets scientifiques, éducatifs et culturels."
