baseURL = 'http://beta.incaya.fr/'
defaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Incaya: reboot"
theme = "incaya"

[social]
    github = "https://github.com/incaya"
    twitter = "https://twitter.com/incayascop"

# Author’s information
[author]
    # Name
    name = "Incaya"
    # Email
    email = "contact@incaya.fr"
    # Avatar
    avatar = "/images/avatar.png"
    # Personal website, default: baseURL
    website = "https://www.incaya.fr"
    # Twitter
    twitter = "incayascop"
    copyright= "CC BY-NC-SA 4.0"

[params]
    siteCreatedTime = "2022-03-16T10:16:58Z"
    siteLogo = "/images/avatar.png"
    author = "Incaya"
    baseline = "Société coopérative de services du numérique"
    description = "A vos côtés pour inventer ! Associations, collectivités, entreprises : nous assurons l'Assistance à Maîtrise d'Ouvrage de votre projet de création ou de refonte de système d'information. Spécialistes de la veille et de l'innovation technique, nous vous conseillons et réalisons des prototypes logiciels et matériels ou des produits pour vos projets scientifiques, éducatifs et culturels."
    mainSections = ["blog"]
    jsonLD = true
    openGraph = true
    twitterCards = true
    copyright= "CC BY-NC-SA 4.0"
    copyrightUrl= "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[taxonomies]
tag = 'tags'
project = 'projects'
