baseURL: https://incaya.fr
defaultContentLanguage: fr
languageCode: fr-fr
title: INCAYA
disableHugoGeneratorInject: true
enableRobotsTXT: true
sitemap:
  changeFreq: monthly
  filename: sitemap.xml
  priority: -1
# autorize raw HTML in Markdown files
markup:
  goldmark:
    renderer:
      unsafe: true
# configure tags
taxonomies:
  tag: tags
disableKinds:
- taxonomy
- term

# Menus footer 
menu:
  footer_contact: 
  - name: Mastodon
    url: https://mastodon.scop.coop/@incaya
    weight: 10
    pre: /icons/mastodon.svg
  - name: Linkedin
    url: https://www.linkedin.com/company/scop-incaya
    pre: /icons/linkedin.svg
    weight: 20
  footer_web: 
  - name: Codeberg
    url: https://codeberg.org/INCAYA
    pre: /icons/codeberg.svg
    weight: 10
  - name: Github
    url: https://github.com/incaya/
    pre: /icons/github.svg
    weight: 20
